syntax = "proto3";

package spine.message.delivery;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.io";
option java_package = "io.spine.message.delivery";
option java_outer_classname = "InboxProto";
option java_multiple_files = true;
option java_generate_equals_and_hash = true;

import "spine/core/ack.proto";
import "spine/server/delivery/inbox.proto";

// The Inbox store API.
service Inbox {

    // Writes a single inbox message to the store.
    rpc WriteMessage(spine.server.delivery.InboxMessage) returns (spine.core.Ack);
}
