/*
 * Copyright (c) 2000-2021 TeamDev. All rights reserved.
 * TeamDev PROPRIETARY and CONFIDENTIAL.
 * Use is subject to license terms.
 */

syntax = "proto3";

package spine.message.delivery;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.io";
option java_package = "io.spine.message.delivery";
option java_outer_classname = "ShardMessagesProto";
option java_multiple_files = true;
option java_generate_equals_and_hash = true;

import "spine/server/delivery/inbox.proto";
import "spine/server/delivery/delivery.proto";

// The Inbox messages grouped by the delivery shard.
message MessagesInShard {
    option (entity).kind = PROJECTION;

    // The shard the message batch belongs to.
    spine.server.delivery.ShardIndex id = 1;

    // Messages stored in the storage.
    //
    // The messages are always stored sorted in chronologically order.
    //
    repeated spine.server.delivery.InboxMessage message = 2;
}
