/*
 * Copyright 2026 CodeMatters, Lda.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

syntax = "proto3";

package spine.delivery;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.io";
option java_package = "io.spine.delivery";
option java_outer_classname = "DeliveryPickUpOutcomeProto";
option java_multiple_files = true;
option java_generate_equals_and_hash = true;

import "spine/delivery/events.proto";
import "spine/delivery/rejections.proto";

// An outcome of the shard pick-up attempt.
//
// This is a Delivery-internal type that is created as a counterpart of `PickUpOutcome`
// introduced in `spine-core` in version `1.9.x`. Delivery servers are already using
// the core library `2.0.x` that doesn't have this type yet. That's why this counterpart
// helps to connect Delivery servers that use core `2.0.x` and Delivery clients that are
// on core `1.9.x`.
//
message DeliveryPickUpOutcome {

    oneof value {

        option (choice).required = true;

        // Signals that the shard is successfully picked up.
        ShardPickedUp picked_up = 1;

        // Signals that the shard could not be picked up as it's already picked by another worker.
        ShardAlreadyPickedUp already_picked_up = 2;
    }
}
