/*
 * Copyright 2026 CodeMatters, Lda.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

syntax = "proto3";

package spine.delivery;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.io";
option java_package = "io.spine.delivery.rejection";
option java_generate_equals_and_hash = true;

import "google/protobuf/timestamp.proto";
import "spine/server/delivery/delivery.proto";

// A shard cannot be picked up because some worker has already picked it up.
message ShardAlreadyPickedUp {

    // The shard in which some worker has picked up work in.
    spine.server.delivery.ShardIndex shard = 1 [(required) = true];

    // The worker that picked up the work in the shard.
    spine.server.delivery.WorkerId worker = 2 [(required) = true];

    // When the worker picked up the work in the shard.
    google.protobuf.Timestamp when_picked = 3 [(required) = true];
}

// A shard cannot be release by the worker.
message UnableToReleaseShard {

    // The shard that should have been released.
    spine.server.delivery.ShardIndex shard = 1 [(required) = true];

    // The worker that was trying to release the `shard`.
    spine.server.delivery.WorkerId worker = 2 [(required) = true];

    Reason reason = 3;

    // The reason why the shard cannot be released.
    message Reason {

        string value = 1 [(required) = true];
    }
}
