/*
 * Copyright (c) 2000-2023 TeamDev. All rights reserved.
 * TeamDev PROPRIETARY and CONFIDENTIAL.
 * Use is subject to license terms.
 */

syntax = "proto3";

package spine.delivery;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.io";
option java_package = "io.spine.delivery";
option java_outer_classname = "SessionsCleanerProto";
option java_multiple_files = true;
option java_generate_equals_and_hash = true;

// A process of cleaning stale sessions.
message SessionsCleaner {
    option (entity).kind = PROCESS_MANAGER;

    // The ID of the cleaner.
    SessionsCleanerId id = 1;
}

// The cleaner identifier.
//
// There is only one instance of the cleaner across the context.
//
message SessionsCleanerId {

    string value = 1 [(required) = true];
}
