/*
 * Copyright 2026 CodeMatters, Lda.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

syntax = "proto3";

package spine.delivery;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.io";
option java_package = "io.spine.delivery";
option java_outer_classname = "ShardSessionRegistryProto";
option java_multiple_files = true;
option java_generate_equals_and_hash = true;

import "google/protobuf/timestamp.proto";

import "spine/server/delivery/delivery.proto";

// A registry of shard session.
//
// The registry tracks who and when has picked up some work and guards the shard
// from being picked up by multiple workers.
//
message ShardSessionRegistry {
    option (entity).kind = AGGREGATE;
    option (entity).visibility = QUERY;

    // The index of the shard this registry is guarding.
    spine.server.delivery.ShardIndex id = 1;

    // The ID of the worker who picked up work from the shard.
    //
    // The value may be empty indicating that no one is currently working with the shard.
    //
    spine.server.delivery.WorkerId worker = 2;

    // The time when the `worker` has picked up the shard.
    //
    // Must be empty when `worker` is also empty.
    //
    google.protobuf.Timestamp when_picked = 3 [(column) = true];
}
