/*
 * Copyright (c) 2000-2026 TeamDev. All rights reserved.
 * TeamDev PROPRIETARY and CONFIDENTIAL.
 * Use is subject to license terms.
 */
syntax = "proto3";

package spine.delivery;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.io";
option java_package = "io.spine.delivery.grpc";
option java_outer_classname = "ShardSessionRegistryServiceProto";
option java_multiple_files = true;
option java_generate_equals_and_hash = true;

import "spine/delivery/commands.proto";
import "spine/delivery/events.proto";
import "spine/delivery/rejections.proto";
import "spine/delivery/pick_up_outcome.proto";

// A service for working with the `ShardSessionRegistry` bypassing Spine's `CommandService`.
service ShardSessionRegistryService {

    // Picks up the shard for processing.
    rpc PickShard(PickUpShard) returns (DeliveryPickUpOutcome);

    // Releases sessions which were picked up earlier that the configured inactivity period.
    rpc ReleaseSessions(ReleaseExpiredSessions) returns (ExpiredSessionsReleased);
}
