/*
 * Copyright 2026 CodeMatters, Lda.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

syntax = "proto3";

package spine.delivery;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.io";
option java_package = "io.spine.delivery.grpc";
option java_outer_classname = "ShardSessionRegistryServiceProto";
option java_multiple_files = true;
option java_generate_equals_and_hash = true;

import "spine/delivery/commands.proto";
import "spine/delivery/events.proto";
import "spine/delivery/rejections.proto";
import "spine/delivery/pick_up_outcome.proto";

// A service for working with the `ShardSessionRegistry` bypassing Spine's `CommandService`.
service ShardSessionRegistryService {

    // Picks up the shard for processing.
    rpc PickShard(PickUpShard) returns (DeliveryPickUpOutcome);

    // Releases sessions that were picked up earlier than the configured inactivity period.
    rpc ReleaseSessions(ReleaseExpiredSessions) returns (ExpiredSessionsReleased);
}
