/*
 * Copyright (c) 2000-2023 TeamDev. All rights reserved.
 * TeamDev PROPRIETARY and CONFIDENTIAL.
 * Use is subject to license terms.
 */

syntax = "proto3";

package spine.message.delivery;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.io";
option java_package = "io.spine.message.delivery.grpc.rejection";
option java_generate_equals_and_hash = true;

import "google/protobuf/timestamp.proto";
import "spine/server/delivery/delivery.proto";


// A shard cannot be picked up because some worker has already picked it up.
message ShardAlreadyPickedUp {

    // The shard in which some worker has picked up work in.
    spine.server.delivery.ShardIndex shard = 1 [(required) = true];

    // The worker that picked up the work in the shard.
    spine.server.delivery.WorkerId worker = 2 [(required) = true];

    // When the worker picked up the work in the shard.
    google.protobuf.Timestamp when_picked = 3 [(required) = true];
}
