/*
 * Copyright (c) 2000-2023 TeamDev. All rights reserved.
 * TeamDev PROPRIETARY and CONFIDENTIAL.
 * Use is subject to license terms.
 */

syntax = "proto3";

package spine.test.message.delivery;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.io";
option java_package = "io.spine.test.message.delivery.client";
option java_outer_classname = "GivenSomethingProto";
option java_multiple_files = true;

message Something {
    option (entity).kind = AGGREGATE;

    string id = 1;
}
