syntax = "proto3";

package spine.message.delivery;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.io";
option java_package = "io.spine.message.delivery.server.command";
option java_outer_classname = "InboxStorageProto";
option java_multiple_files = true;
option java_generate_equals_and_hash = true;

import "spine/server/delivery/inbox.proto";

// The storage of an Inbox.
message InboxStorage {
    option (entity).kind = PROJECTION;

    // The ID of the Inbox this storage is linked to.
    spine.server.delivery.InboxId id = 1;

    // Messages stored in the storage.
    repeated spine.server.delivery.InboxMessage message = 2;
}
