# syntax=docker/dockerfile:1

FROM amazoncorretto:11

# The Traffic Control utility manages queueing disciplines, their classes and
# attached filters and actions. It is the standard tool to configure QoS in Linux.
RUN yum install iproute-tc -y
