name: Build PR

on:
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build-server:
    name: Build Server
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16'
          java-package: jdk
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build Server
        run: ./gradlew :simple-server:build --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-client:
    name: Build Client
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Prepare local server container
        run: ./gradlew :server-cloud-run:jibDockerBuild :simple-server-cloud-run:jibDockerBuild
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Client
        run: |
          cd client
          ./gradlew build --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-admin-web-client:
    name: Build Admin Web Client
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 19.6.0
      - name: Build Quasar SPA
        run: ./gradlew :admin-ui:qbuild --stacktrace
